### ISSUE TITLE
Bugs and Usability

### ISSUE THREAD

**Issue by tnscorcoran** [3scale/nginx-oauth-templates#20]
There are a few issues with the latest templates - in the Authorisation Code Grant Flow - with Token generation.
1) 
With the resolver 8.8.8.8 8.8.4.4; it can't resolve the 3scale back end.
Anything I need to do to get this working? 
I reverted to using the upstream like used to be used. Any reason why we shouldn't still use the upstream? Which works.
When we were onsite at Putnam, we had to remove this as well. 

2)
In the nginx.conf location: 
/_threescale/redirect_uri_matches
it passes in the variable $client_secret which is not available and used not be passed in. Seems to work without it. Are we OK to omit it?

3)
In get_token.lua, the store_token function on line 39 expects a parameter expires_in. Yet the call to it on line 69 doesn't pass that in - causing the call to crash. We could add a default like 3600 - along with a comment that this should be changed to your desired TTL.

4)
Line 52 of get_token.lua contains a non existent variable token. This causes the call to crash. It should be access_token.

**Comment by mpguerra** [comment]
1) This works for me. If for some reason google dns is blocked by a client, they can put in their own dns server there. I will add a comment in future versions of the templates. Regarding the upstream definition, this was changed to keep the files as close to the downloaded ones as possible. 

2) removed

3) Added a check for null. There is another version coming that sets a default. For now if it is sent it will be taken into account, otherwise it is set to -1 for no expiry

4) fixed
